### ISSUE TITLE
Submenu Page without any function

### ISSUE THREAD

**Issue by sixtyseven-multimedia** [WebMaestroFr/wm-settings#2]
I like to create a Credits page as a submenu item under a topmenu created  by your class. The Layout of the page is provided by a public function inside of my plugin class. Any idea how tto achieve this?  Thanks for help and greetings from germany

**Comment by WebMaestroFr** [comment]
`add_submenu_page( 'top_page_id', 'Credits', 'Credits', 'manage_options', 'credits_page_id', array( 'Your_Plugin_Class', 'mublic_method_credits' ) );`

**Comment by sixtyseven-multimedia** [comment]
Unfortunately, your suggestion leads to a 404 Error. What did not work either was this one: 

add_submenu_page( 'top_page_id', 'Credits', 'Credits', 'manage_options', 'admin.php?page=credits_page_id', array($this, 'credits_page_callback') );

This produces the insufficient rights error.

Do you have any other idea?

**Comment by sixtyseven-multimedia** [comment]
I came up with some sort of workaround. Works, but is not the way I like to use it. I added the following to the method admin_menu():

`if(file_exists('credits.inc.php')){
            if ( $this->menu['parent'] ) {  
                $credits_parent =  $this->menu['parent'];
            } else {
                $credits_parent =  $this->page;
            }
            add_submenu_page( $credits_parent, 'Credits', 'Credits', $this->menu['capability'], $this->page.'_credits', array($this, 'credits_page_callback') );
          }`

and added 
`public function credits_page_callback() {
        require_once('credits.inc.php');
      }`

A bit dirty, but at least works. Would be nice if you have a bether solution, though ...

**Comment by WebMaestroFr** [comment]
Wrap the function "add_submenu_page" with the "admin_menu" hook (https://codex.wordpress.org/Plugin_API/Action_Reference/admin_menu). You can do that cleanly – from your plugin, or theme's functions.php.

`add_action( 'admin_menu', 'my_admin_menu' );
function my_admin_menu() {
  add_submenu_page( ... );
}`

No need to edit the class as WordPress menu functions are working fine with it, just make sure you set correct parameters. I did create a few subpage without problems.

I don't know how to guide you more specifically, it is hard to overview the issue. But I truly hope you'll solve it right.
