### ISSUE TITLE
Default values for settings

### ISSUE THREAD

**Issue by sixtyseven-multimedia** [WebMaestroFr/wm-settings#3]
The more I work with your class, the better I like it, thanks again for givng this to the community.

Could you give me a hint, how I could populate the settings fields with default values that I can provide with my plugin?

**Comment by WebMaestroFr** [comment]
You are welcome !

There is a ['default' parameter](http://webmaestro.fr/wordpress-settings-api-options-pages/#sections-and-fields) for each field, it is probably what you are looking for.

**Comment by sixtyseven-multimedia** [comment]
Indeed, I found it, sorry to bother you.

**Comment by WebMaestroFr** [comment]
No problem.
